# Generated by Django 4.0.4 on 2022-05-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_url_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='htmlcode',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
