# Generated by Django 4.0.4 on 2022-05-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_site_htmlcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='htmlcode',
        ),
    ]
