# Generated by Django 4.0.4 on 2022-05-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_site_htmlcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
    ]
